CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS bmi_records (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  weight NUMERIC NOT NULL,
  bmi NUMERIC NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS desired_weight_records(
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  weight NUMERIC NOT NULL,
  desired_weight NOT NULL,
  proteins NOT NULL,
  carbs NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);